--
-- PostgreSQL database dump
--

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categoria_consumidor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categoria_consumidor (
    id bigint NOT NULL,
    nome character varying(50) NOT NULL
);


--
-- Name: categoria_consumidor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categoria_consumidor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_consumidor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: faixa_consumo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.faixa_consumo (
    id bigint NOT NULL,
    fim integer NOT NULL,
    inicio integer NOT NULL,
    valor_unitario numeric(10,2) NOT NULL,
    categoria_id bigint NOT NULL,
    tabela_id bigint NOT NULL
);


--
-- Name: faixa_consumo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.faixa_consumo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faixa_consumo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tabela_tarifaria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tabela_tarifaria (
    id bigint NOT NULL,
    data_vigencia date NOT NULL,
    nome character varying(100) NOT NULL,
    ativo boolean NOT NULL
);


--
-- Name: tabela_tarifaria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tabela_tarifaria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tabela_tarifaria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categoria_consumidor categoria_consumidor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria_consumidor
    ADD CONSTRAINT categoria_consumidor_pkey PRIMARY KEY (id);


--
-- Name: faixa_consumo faixa_consumo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faixa_consumo
    ADD CONSTRAINT faixa_consumo_pkey PRIMARY KEY (id);


--
-- Name: tabela_tarifaria tabela_tarifaria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tabela_tarifaria
    ADD CONSTRAINT tabela_tarifaria_pkey PRIMARY KEY (id);


--
-- Name: categoria_consumidor ukjjb6lrerqj3uud1d3cf3e8i8q; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria_consumidor
    ADD CONSTRAINT ukjjb6lrerqj3uud1d3cf3e8i8q UNIQUE (nome);


--
-- Name: faixa_consumo fk6kfes3g7myk19g7ttylwhy8eh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faixa_consumo
    ADD CONSTRAINT fk6kfes3g7myk19g7ttylwhy8eh FOREIGN KEY (categoria_id) REFERENCES public.categoria_consumidor(id);


--
-- Name: faixa_consumo fkcgdov3k6ypwi6r2th8i53vg91; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faixa_consumo
    ADD CONSTRAINT fkcgdov3k6ypwi6r2th8i53vg91 FOREIGN KEY (tabela_id) REFERENCES public.tabela_tarifaria(id);


--
-- PostgreSQL database dump complete
--

